
$BKHIROU[0] = '1';
$BKHIROU[1] = '3';
$BKHIROU[2] = '6';
$BKHIROU[3] = '2';
$BKHIROU[4] = '2';
$BKHIROU[5] = '0';
$BKHIROU[6] = '0';

$HKHIROU[0] = '3';
$HKHIROU[1] = '5';
$HKHIROU[2] = '7';
$HKHIROU[3] = '4';
$HKHIROU[4] = '5';
$HKHIROU[5] = '7';
$HKHIROU[6] = '5';

$SKHIROU[0] = '2';
$SKHIROU[1] = '1';
$SKHIROU[2] = '0';
$SKHIROU[3] = '0';
$SKHIROU[4] = '0';
$SKHIROU[5] = '0';
$SKHIROU[6] = '0';

$BHHIROU[0] = '0';
$BHHIROU[1] = '2';
$BHHIROU[2] = '2';
$BHHIROU[3] = '1';
$BHHIROU[4] = '1';
$BHHIROU[5] = '2';
$BHHIROU[6] = '2';

#####

$BKIKURITU[0] = '0';
$BKIKURITU[1] = '0';
$BKIKURITU[2] = '0';
$BKIKURITU[3] = '0';
$BKIKURITU[4] = '-15';
$BKIKURITU[5] = '0';
$BKIKURITU[6] = '0';

$HKIKURITU[0] = '0';
$HKIKURITU[1] = '0';
$HKIKURITU[2] = '0';
$HKIKURITU[3] = '0';
$HKIKURITU[4] = '0';
$HKIKURITU[5] = '0';
$HKIKURITU[6] = '0';

$SKIKURITU[0] = '0';
$SKIKURITU[1] = '-15';
$SKIKURITU[2] = '-100';
$SKIKURITU[3] = '0';
$SKIKURITU[4] = '0';
$SKIKURITU[5] = '0';
$SKIKURITU[6] = '0';

$BHIKURITU[0] = '0';
$BHIKURITU[1] = '5';
$BHIKURITU[2] = '0';
$BHIKURITU[3] = '0';
$BHIKURITU[4] = '0';
$BHIKURITU[5] = '0';
$BHIKURITU[6] = '0';
#####

$BKHUSYOUBOU[0] = '0';
$BKHUSYOUBOU[1] = '0';
$BKHUSYOUBOU[2] = '0';
$BKHUSYOUBOU[3] = '0';
$BKHUSYOUBOU[4] = '3';
$BKHUSYOUBOU[5] = '0';
$BKHUSYOUBOU[6] = '0';

$HKHUSYOUBOU[0] = '0';
$HKHUSYOUBOU[1] = '0';
$HKHUSYOUBOU[2] = '0';
$HKHUSYOUBOU[3] = '0';
$HKHUSYOUBOU[4] = '0';
$HKHUSYOUBOU[5] = '0';
$HKHUSYOUBOU[6] = '0';

$SKHUSYOUBOU[0] = '0';
$SKHUSYOUBOU[1] = '1';
$SKHUSYOUBOU[2] = '10';
$SKHUSYOUBOU[3] = '0';
$SKHUSYOUBOU[4] = '0';
$SKHUSYOUBOU[5] = '0';
$SKHUSYOUBOU[6] = '0';

$BHHUSYOUBOU[0] = '0';
$BHHUSYOUBOU[1] = '5';
$BHHUSYOUBOU[2] = '0';
$BHHUSYOUBOU[3] = '0';
$BHHUSYOUBOU[4] = '0';
$BHHUSYOUBOU[5] = '0';
$BHHUSYOUBOU[6] = '0';
1;